name = "hex-primality"
defaultTargets = ["HexPrimality"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "a47240943e925951a676d1a1c2f2a615ae68fdef"

[[require]]
name = "HexArith"
git = "https://github.com/leanprover/hex-arith.git"
rev = "ea246536c442464a68210ecce973eb7708968f59"

[[lean_lib]]
name = "HexPrimality"
