name = "hex-primality"
defaultTargets = ["HexPrimality"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "6ad58796dca6bae4936003412816e4e844055558"

[[require]]
name = "HexArith"
git = "https://github.com/leanprover/hex-arith.git"
rev = "f6ea40210366e9d53f77439df7961d0bc5b1d02f"

[[lean_lib]]
name = "HexPrimality"
